-- Skapa interest_applications tabell (om den inte finns redan)
CREATE TABLE IF NOT EXISTS interest_applications (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id uuid REFERENCES orgs(id) ON DELETE CASCADE,
  parent_name text NOT NULL,
  parent_email text NOT NULL,
  parent_phone text NOT NULL,
  owner_city text,
  owner_address text,
  dog_name text NOT NULL,
  dog_breed text,
  dog_birth date,
  dog_age integer,
  dog_gender text CHECK (dog_gender IN ('hane', 'tik')),
  dog_size text CHECK (dog_size IN ('small', 'medium', 'large')),
  dog_height_cm integer,
  subscription_type text,
  preferred_start_date date,
  preferred_days text[],
  special_needs text,
  special_care_needs text,
  is_neutered boolean DEFAULT false,
  is_escape_artist boolean DEFAULT false,
  destroys_things boolean DEFAULT false,
  not_house_trained boolean DEFAULT false,
  previous_daycare_experience boolean,
  gdpr_consent boolean DEFAULT false,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'contacted', 'accepted', 'declined')),
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Lägg till testdata för intresseanmälningar
INSERT INTO interest_applications (
  org_id,
  parent_name,
  parent_email,
  parent_phone,
  owner_city,
  owner_address,
  dog_name,
  dog_breed,
  dog_birth,
  dog_gender,
  dog_height_cm,
  subscription_type,
  preferred_start_date,
  preferred_days,
  special_care_needs,
  is_neutered,
  is_escape_artist,
  destroys_things,
  not_house_trained,
  gdpr_consent,
  status,
  notes
) VALUES 
-- Pending ansökan
(
  (SELECT id FROM orgs WHERE slug = 'demo' LIMIT 1),
  'Maria Svensson',
  'maria.svensson@example.com',
  '0701234567',
  'Stockholm',
  'Storgatan 12',
  'Bella',
  'Golden Retriever',
  '2023-03-15',
  'tik',
  55,
  'heltid',
  '2025-11-15',
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
  'Bella är jättesnäll men blir lite nervös i stora grupper.',
  true,
  false,
  false,
  false,
  true,
  'pending',
  'Ny ansökan inkom via webbformulär'
),
-- Contacted ansökan
(
  (SELECT id FROM orgs WHERE slug = 'demo' LIMIT 1),
  'Erik Andersson',
  'erik.andersson@example.com',
  '0709876543',
  'Göteborg',
  'Hamngatan 5',
  'Max',
  'Border Collie',
  '2022-08-20',
  'hane',
  48,
  'deltid_3',
  '2025-12-01',
  ARRAY['monday', 'wednesday', 'friday'],
  'Max har mycket energi och behöver stimulans.',
  false,
  false,
  false,
  false,
  true,
  'contacted',
  'Ringde och pratade med Erik 2025-10-28. Vill börja i december.'
),
-- Accepted ansökan (redo att överföra)
(
  (SELECT id FROM orgs WHERE slug = 'demo' LIMIT 1),
  'Lisa Johansson',
  'lisa.johansson@example.com',
  '0703456789',
  'Malmö',
  'Södergatan 20',
  'Charlie',
  'Labrador',
  '2023-06-10',
  'hane',
  58,
  'heltid',
  '2025-11-10',
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
  'Charlie är en lugn och snäll hund som älskar vatten.',
  true,
  false,
  false,
  false,
  true,
  'accepted',
  'Ansökan godkänd! Lisa har bekräftat startdatum och betalat insättning.'
),
-- Declined ansökan
(
  (SELECT id FROM orgs WHERE slug = 'demo' LIMIT 1),
  'Anders Karlsson',
  'anders.karlsson@example.com',
  '0705678901',
  'Uppsala',
  'Kungsgatan 8',
  'Rocky',
  'Rottweiler',
  '2021-02-14',
  'hane',
  65,
  'heltid',
  '2025-11-01',
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
  'Rocky har haft beteendeproblem tidigare men jobbar med det.',
  false,
  true,
  true,
  true,
  true,
  'declined',
  'Tyvärr passade inte Rocky för vår dagisgrupp just nu. Rekommenderade enskilda promenader istället.'
);

COMMENT ON TABLE interest_applications IS 'Ansökningar från hundägare som vill ha dagisplats';
COMMENT ON COLUMN interest_applications.status IS 'pending = ny ansökan, contacted = kontaktad, accepted = godkänd (redo att överföra), declined = avböjd';
