// Officiell lista över hundraser som används i DogPlanner
// Sorterad alfabetiskt för enkel navigation (a-ö)

export const DOG_BREEDS = [
  "Affenpinscher",
  "Afghanhund",
  "Airedaleterrier",
  "Akita",
  "Alano español",
  "Alaskan husky",
  "Alaskan klee kai",
  "Alaskan malamute",
  "Alpenländische dachsbracke",
  "American akita",
  "American bully",
  "American eskimo dog",
  "American foxhound",
  "American hairless terrier",
  "American miniature schnauzer",
  "American staffordshire terrier",
  "American toy fox terrier",
  "American wolfdog",
  "Amerikansk bulldog",
  "Amerikansk cocker spaniel",
  "Anatolisk herdehund",
  "Appenzeller sennenhund",
  "Australian cattledog",
  "Australian kelpie",
  "Australian shepherd",
  "Australian stock dog/working kelpie",
  "Australisk terrier",
  "Azawakh",
  "Barbet",
  "Basenji",
  "Basset artésien normand",
  "Basset bleu de gascogne",
  "Basset fauve de bretagne",
  "Basset hound",
  "Bayersk viltspårhund",
  "Beagle",
  "Bearded collie",
  "Beauceron",
  "Bedlingtonterrier",
  "Belgisk vallhund/ groenendael",
  "Belgisk vallhund/ laekenois",
  "Belgisk vallhund/ malinois",
  "Belgisk vallhund/ tervueren",
  "Bergamasco",
  "Berger des pyrénées a face rase",
  "Berger des pyrénées a poil long",
  "Berger picard",
  "Berner sennenhund",
  "Bichon frisé",
  "Bichon havanais",
  "Biewer",
  "Biewer terrier",
  "Black and tan coonhound",
  "Blandras",
  "Blandras aussiedoodle",
  "Blandras australian cobberdog",
  "Blandras australian labradoodle",
  "Blandras bernedoodle",
  "Blandras cavachon",
  "Blandras cavapoo",
  "Blandras cockerpoo",
  "Blandras goldador",
  "Blandras goldendoodle",
  "Blandras havapoo",
  "Blandras labradoodle",
  "Blandras maltichon",
  "Blandras maltipoo",
  "Blandras pomchi",
  "Blandras pomsky",
  "Blandras schabrador",
  "Blandras shih-poo",
  "Blandras shiloh shepherd",
  "Blandras tamaskan dog",
  "Blodhund",
  "Bluetick coonhound",
  "Boerboel",
  "Bolognese",
  "Border collie",
  "Borderterrier",
  "Borzoi",
  "Bosanski ostrodlaki gonic-barak",
  "Bostonterrier",
  "Bouvier des flandres",
  "Boxer",
  "Bracco italiano",
  "Braque d'auvergne",
  "Braque du bourbonnais",
  "Braque francais, type pyrénées",
  "Breton",
  "Briard",
  "Briquet griffon vendeen",
  "Broholmer",
  "Bullmastiff",
  "Bullterrier",
  "Cairnterrier",
  "Canaan dog",
  "Canadian eskimo dog",
  "Cane corso",
  "Cao da serra de aires",
  "Cão da serra da estrela, korthårig",
  "Cão da serra da estrela, långhårig",
  "Cão de castro laboreiro",
  "Cão fila de sâo miguel",
  "Catahoula leopard dog",
  "Cavalier king charles spaniel",
  "Ceskoslovenský vlcak",
  "Cesky fousek",
  "Cesky terrier",
  "Chart polski",
  "Chesapeake bay retriever",
  "Chihuahua",
  "Chihuahua, korthårig",
  "Chihuahua, långhårig",
  "Chinese chongqing dog",
  "Chinese crested dog",
  "Chodsky pes",
  "Chow-chow",
  "Cimarrón uruguayo",
  "Ciobanesc romanesc corb",
  "Ciobanesc romanesc de bucovina",
  "Ciobanesc romanesc mioritic",
  "Cirneco dellétna",
  "Clumber spaniel",
  "Cocker spaniel",
  "Collie",
  "Collie, korthårig",
  "Collie, långhårig",
  "Continental bulldog",
  "Coton de tuléar",
  "Cretan hound",
  "Cruce bodeguero",
  "Curly coated retriever",
  "Dalmatiner",
  "Dandie dinmont terrier",
  "Dansk spids",
  "Dansk/svensk gårdshund",
  "Deutsche bracke",
  "Dobermann",
  "Dogo argentino",
  "Dogo canario",
  "Dogue de bordeaux",
  "Drentsche patrijshond",
  "Drever",
  "Dunkerstövare",
  "Dvärgpinscher",
  "Dvärgschnauzer",
  "Dvärgschnauzer, peppar & salt",
  "Dvärgschnauzer, svart",
  "Dvärgschnauzer, svart & silver",
  "Dvärgschnauzer, vit",
  "Dvärgspets",
  "Engelsk bulldogg",
  "Engelsk setter",
  "Engelsk springer spaniel",
  "English toy terrier",
  "Entlebucher sennenhund",
  "Épagneul bleu de picardie",
  "Épagneul de saint usufge",
  "Épagneul francais",
  "Épagneul picard",
  "Erdélyi kopó",
  "Estlandsstövare",
  "Eurasier",
  "Faraohund",
  "Field spaniel",
  "Fila brasileiro",
  "Finsk lapphund",
  "Finsk spets",
  "Finsk stövare",
  "Flatcoated retriever",
  "Foxhound",
  "Fransk bulldogg",
  "Galgo español",
  "Gammal dansk hönsehund",
  "Golden retriever",
  "Gonczy polski",
  "Gordonsetter",
  "Gos d'atura catala",
  "Gotlandsstövare",
  "Grand basset griffon vendéen",
  "Grand bleu de gascogne",
  "Grand danois",
  "Great japanese dog",
  "Greyhound",
  "Griffon belge",
  "Griffon bruxellois",
  "Griffon d'arret a poil dur/korthals",
  "Griffon fauve de bretagne",
  "Griffon nivernais",
  "Grosser münsterländer",
  "Grosser schweizer sennenhund",
  "Grönlandshund",
  "Haldenstövare",
  "Hamiltonstövare",
  "Hannoveransk viltspårhund",
  "Hedehund",
  "Hellinikos ichnilatis",
  "Hokkaido",
  "Hollandse herdershond",
  "Hollandse herdershond, korthårig",
  "Hollandse herdershond, långhårig",
  "Hollandse herdershond, strävhårig",
  "Hovawart",
  "Hrvatski ovcar",
  "Hygenstövare",
  "Hälleforshund",
  "Irish glen of imaal terrier",
  "Irish softcoated wheaten terrier",
  "Irländsk röd och vit setter",
  "Irländsk röd setter",
  "Irländsk terrier",
  "Irländsk varghund",
  "Irländsk vattenspaniel",
  "Isländsk fårhund",
  "Istarski kratkodlaki gonic",
  "Italiensk vinthund",
  "Jack russell terrier",
  "Jakutskaja lajka",
  "Japanese chin",
  "Japansk spets",
  "Juzjnorusskaja ovtjarka",
  "Jämthund",
  "Kai",
  "Kangal",
  "Karels björnhund",
  "Karpatsisk herdehund",
  "Kavkazskaja ovtjarka",
  "Keeshond",
  "Kerry blue terrier",
  "King charles spaniel",
  "Kishu",
  "Kleiner münsterländer",
  "Kokoni",
  "Komondor",
  "Koolie",
  "Korea jindo dog",
  "Korthårig vorsteh",
  "Kraski ovcar",
  "Kritikos ichnilatis",
  "Kromfohrländer",
  "Kuvasz",
  "Labrador retriever",
  "Lagotto romagnolo",
  "Lakelandterrier",
  "Lancashire heeler",
  "Landseer",
  "Lapsk vallhund",
  "Leonberger",
  "Lhasa apso",
  "Louisiana catahoula leopard",
  "Lurcher",
  "Långhårig vorsteh",
  "Löwchen",
  "Magyar agar",
  "Malteser",
  "Manchesterrier",
  "Maremmano-abruzzese",
  "Mastiff",
  "Mastin español",
  "Mastino napoletano",
  "Mexikansk nakenhund",
  "Mexikansk nakenhund, liten",
  "Mexikansk nakenhund, mellan",
  "Mexikansk nakenhund, stor",
  "Mini malteser",
  "Miniature american shepherd",
  "Miniatyrbullterrier",
  "Mops",
  "Mudi",
  "Nederlandse kooikerhondje",
  "Newfoundlandshund",
  "Nihon teria",
  "Norfolkterrier",
  "Norrbottenspets",
  "Norsk buhund",
  "Norsk lundehund",
  "Norsk älghund, grå",
  "Norsk älghund, svart",
  "Norwichterrier",
  "Nova scotia duck tolling retriever",
  "Ogar polski",
  "Old english sheepdog",
  "Olde english bulldog",
  "Otterhound",
  "Papillon",
  "Parson russell terrier",
  "Parti schnauzer",
  "Patterdale terrier",
  "Pekingese",
  "Perdigueiro portugues",
  "Perro de agua espanol",
  "Perro de pastor vasco",
  "Perro dogo mallorquin/ca de bou",
  "Perro majorero",
  "Perro sin pelo del pel perú",
  "Perro sin pelo del pel perú, grande",
  "Perro sin pelo del pel perú, médio",
  "Perro sin pelo del pel perú, pequeno",
  "Petit basset griffon vendéen",
  "Petit bleu de gascogne",
  "Petit brabancon",
  "Phalene",
  "Phu quoc ridgeback",
  "Pinscher",
  "Plotthound",
  "Podenco andaluz",
  "Podenco canario",
  "Podenco ibicenco",
  "Podenco maneto",
  "Podengo portug.,cerdoso/pequeno",
  "Podengo portugues",
  "Podengo portugues, liso/médio",
  "Podengo portugues, liso/pequeno",
  "Pointer",
  "Polski owczarek nizinnny",
  "Polski owczarek podhalanski",
  "Polski spaniel myslowski",
  "Pomeranian",
  "Porcelaine",
  "Portugisisk vattenhund",
  "Posavski gonic",
  "Prazský krysarík",
  "Pudel",
  "Pudel, dvärg",
  "Pudel, mellan",
  "Pudel, stor",
  "Pudel, toy",
  "Pudelpointer",
  "Puli",
  "Pumi",
  "Pyrenéerhund",
  "Pyreneisk mastiff",
  "Rafiero do alentejo",
  "Rat terrier",
  "Ratero mallorquin",
  "Ratonero bodeguero andaluz",
  "Rhodesian ridgeback",
  "Riesenschnauzer",
  "Riesenschnauzer, peppar & salt",
  "Riesenschnauzer, svart",
  "Rottweiler",
  "Russkaja gontjaja",
  "Russkaya tsvetnaya bolonka",
  "Russkiy toy",
  "Rysk europeisk lajka",
  "Rysk fläckig stövare",
  "Rysk svart terrier",
  "Saarloos wolfhond",
  "Sabueso español",
  "Saluki",
  "Samojedhund",
  "Sankt bernhardshund",
  "Sankt bernhardshund, korthårig",
  "Sankt bernhardshund, långhårig",
  "Sarplaninac",
  "Schapendoes",
  "Schillerstövare",
  "Schipperke",
  "Schnauzer, peppar & salt",
  "Schnauzer, svart",
  "Schäfer",
  "Schweiziska stövare/ berner",
  "Schweiziska stövare/ jura",
  "Schweiziska stövare/ luzerner",
  "Schweiziska stövare/ schwyzer",
  "Sealyhamterrier",
  "Serbski gonic",
  "Shar-pei",
  "Shetland sheepdog",
  "Shiba",
  "Shih tzu",
  "Shikoku",
  "Siberian husky",
  "Silken windhound",
  "Silken windsprite",
  "Silky terrier",
  "Skotsk hjorthund",
  "Skotsk terrier",
  "Skånsk terrier",
  "Skyeterrier",
  "Sloughi",
  "Slovenský cuvac",
  "Slovenský hrubosrsty stavac",
  "Slovensky kopov",
  "Släthårig foxterrier",
  "Smålandsstövare",
  "Spinone",
  "Sredneasiatskaja ovtjarka",
  "Stabyhoun",
  "Staffordshire bullterrier",
  "Steirische rauhhaarbracke",
  "Strävhårig foxterrier",
  "Strävhårig vorsteh",
  "Sussex spaniel",
  "Svart terrier",
  "Svensk lapphund",
  "Svensk varghund",
  "Svensk vit älghund",
  "Taigan",
  "Taiwan dog",
  "Tax",
  "Tax, korthårig dvärg",
  "Tax, korthårig kanin",
  "Tax, korthårig normalstor",
  "Tax, långhårig dvärg",
  "Tax, långhårig kanin",
  "Tax, långhårig normalstor",
  "Tax, strävhårig dvärg",
  "Tax, strävhårig kanin",
  "Tax, strävhårig normalstor",
  "Tenterfield terrier",
  "Terrier brasileiro",
  "Thai bangkaew dog",
  "Thai ridgeback dog",
  "Tibetansk mastiff",
  "Tibetansk spaniel",
  "Tibetansk terrier",
  "Tornjak",
  "Tosa",
  "Treeing walker coonhound",
  "Tysk spets",
  "Tysk spets/dvärg",
  "Tysk spets/grosspitz",
  "Tysk spets/keeshond",
  "Tysk spets/kleinspitz",
  "Tysk spets/mittelspitz",
  "Tyskjakttterrier",
  "Ungersk vizsla",
  "Ungersk vizsla, korthårig",
  "Ungersk vizsla, strävhårig",
  "Vit herdehund",
  "Vit schäfer",
  "Volpino italiano",
  "Vorsteh",
  "Vostotjnoevropejskaja ovtjarka",
  "Västgötaspets",
  "Västsibirisk laika",
  "Wachtelhund",
  "Weimaraner",
  "Weimaraner, korthårig",
  "Weimaraner, långhårig",
  "Welsh corgi, cardigan",
  "Welsh corgi, pembroke",
  "Welsh sheepdog",
  "Welsh springer spaniel",
  "Welshtetrier",
  "West highland white terrier",
  "Wetterhoun",
  "Whippet",
  "Working kelpie",
  "Xoloitzuintle",
  "Xoloitzuintle, liten",
  "Xoloitzuintle, mellan",
  "Xoloitzuintle, stor",
  "Yorkshireterrier",
  "Österreichischer pinscher",
  "Östsibirisk laika",
] as const;

export type DogBreed = (typeof DOG_BREEDS)[number];
